name: build project

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: write
        strategy:
            fail-fast: false
        steps:
            - name: checkout Repository
              uses: actions/checkout@v4
            - name: setup NodeJS
              uses: actions/setup-node@v4
              with: 
                node-version: '20'
                cache: 'npm'
            - name: install dependencies
              run: npm ci
            - name: build the software
              run: npm run make --if-present >> $GITHUB_OUTPUT
            - name: zip folder
              run: Compress-Archive -Path out/achievementlist-win32-x64/* achievementList.zip
            - name: create a release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "achievementList.zip"
                draft: true
                tag: v1.0.2