name: build project

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: 
                node-version: '20'
                cache: 'npm'
            - run: npm ci
            - run: npm run make --if-present >> $GITHUB_OUTPUT
            - uses: ncipollo/release-action@v1
              with:
                artifacts: "*.zip"
                draft: true